---
search_recipe:
  scope_statements:
    - "Child online safety and privacy"
    - "Protecting children in the digital age"
    - "Protecing children from online threats"
    - "Protecting children from cyber bullying"
    - "Ensuring children's safety online"
    - "Ensuring children's privacy online"
    - "Helping parents protect their children online"
    - "Helping parents inform their children about online safety"
    - "Helping parents monitor their children's online activity"
    - "Helping children with digital addiction"

  keyword_sets:
    - set_name: "Domain keywords"
      keywords:
        - "child"
        - "children"
        - "infant"
        - "baby"
        - "babies"
        - "toddler"
        - "toddlers"
        - "pregnancy"
        - "parent"
        - "mother"
        - "father"
        - "family"
        - "pupil"
        - "teenager"
        - "teen"

    - set_name: "Tech keywords"
      keywords:
        - "cybersecurity"
        - "online safety"
        - "data protection"
        - "encryption"
        - "malware"
        - "phishing"
        - "firewall"
        - "identity theft"
        - "cyber threats"
        - "cyberattack"
        - "cyber attack"
        - "data breach"
        - "social engineering"
        - "threat intelligence"
        - "penetration testing"
        - "cyber defence"
        - "cyber defense"
        - "cyber forensics"
        - "ransomware"
        - "zero day exploit"
        - "cloud security"
        - "cyber bullying"
        - "digital addiction"
        - "inappropriate content"
