---
search_recipe:
  scope_definition:
    - "Statement 1"
    - "Statement 2"
    - "Further statements as necessary"

  keyword_sets:
    - set_name: "Primary keywords"
      prompt: |
        Generate a comprehensive list of 25-50 relevant keywords and key phrases using the input text and instructions provided by the user.
        These keywords and phrases should be suitable for searching databases related to research projects, companies and other data.
        Ensure the output is a list of single or multi-word keywords only.
        Focus on keywords that are specific to energy, renewables, low carbon heating and similar topics.
      keywords:
        - ""

    - set_name: "Secondary keywords"
      prompt: |
        Generate a comprehensive list of 25-50 relevant keywords and key phrases using the input text and instructions provided by the user.
        These keywords and phrases should be suitable for searching databases related to research projects, companies and other data.
        Ensure the output is a list of single or multi-word keywords only.
        Focus on keywords that are specific to energy, renewables, low carbon heating and similar topics.
      keywords:
        - ""

  keyword_search:
    enabled: true
    search_parameters:
      max_results: 50

  vector_search:
    enabled: true
    search_parameters:
      max_results: 50

  ai_filtering:
    enabled: true

  outputs:
    - crunchbase_organisations
    - crunchbase_people
    - gtr_projects
    - gtr_organisations
    - gtr_persons
