---
search_recipe:
  scope_statements:
    - "Support for weight loss drugs"
    - "Research on GLP-1"
    - "Companies working on weight loss drugs"
    - "Wrap around support for weight loss drug patients"

  keyword_sets:
    - set_name: "core GLP-1 terms"
      keywords:
        - "GLP-1"
        - "Glucagon-like peptide-1"
        - "incretin"
        - "peptide theraputics"
        - "weight loss drugs"
    - set_name: "additional GLP-1 terms"
      keywords:
        - "obesity treatment"
        - "diabetes management"
        - "type 2 diabetes"
        - "metabolic disorders"
        - "blood glucose control"
        - "insulin regulation"
        - "Semaglutide"
        - "Liraglutide"
        - "Dulaglutide"
        - "Exenatide"
        - "Tirzepatide"
        - "Rybelsus"
        - "Ozempic"
        - "Wegovy"
        - "Saxenda"
