---
mission_statements:
  ASF: |
      A Sustainable Future
      Objective: To accelerate the decarbonisation of household activities in the UK and improve productivity levels. The target is a 28% reduction in household carbon emissions from 2019 levels by 2030, aligning with the UK's net-zero goals.
      Approach:
      Clean Heating Solutions: Promoting the adoption of low-carbon heating technologies, such as heat pumps, to reduce emissions from domestic heating.
      Policy Advocacy: Developing and recommending policy frameworks that support the transition to sustainable household energy practices.
      Skill Development: Addressing the shortage of qualified professionals to install and maintain green technologies by investing in training and capacity building.
